config:
  env:
  cppcheck:
    pattern: 'build/linux-builds/result/cppcheck.*.xml'
  cmake:
    pattern: 'build/linux-builds/result/make.*'
  gcc:
    pattern: 'build/linux-builds/result/make.*'
  archiveArtifacts:
    artifacts: 'build/linux-builds/result/*'


stages:
  - x86_build

stage:
  x86_build:
    node: docker
    docker:
      image: sharaku/cross-build
    script:
     - sh: cd build/linux-builds && make
    result: 'build/linux-builds/result/*'
